### ISSUE TITLE
coedit.re is unavailable

### ISSUE THREAD

**Issue by almereyda** [coast-team/mute#110]
Trying to open the projects website at coedit.re will result in a connection timeout.

**Comment by oster** [comment]
You are right. CoEdit.re is no more available. We are in the process of installing a new public instance.

**Comment by rigelk** [comment]
The app is now live at https://mutehost.loria.fr/

**Comment by sneakers-the-rat** [comment]
Getting an internal server error on the HTTPS cert on https://mutehost.loria.fr/

**Comment by BaptisteHubert** [comment]
App has been migrated to https://mute.loria.fr
