### ISSUE TITLE
As a User I want to add basic styles (bold,  italic...) to the document using toolbar

### ISSUE THREAD

**Issue by kalitine** [coast-team/mute#20]
# Toolbar
It is created via [Angular Material Button Toggle](https://material.angular.io/components/button-toggle/overview)

## Toolbar buttons (ticked if functionnal)
- [x] bold
- [x] italic
- [x] strikethrough
- [x] link (url focused in any case)
- [x] quote (force the syntax to appear at beginning of lines)
- [x] headers (force the syntax to appear at beginning of lines)
- [x] lists (force the syntax to appear at beginning of lines)
### About toggling
- [x] buttons must be toggled when the related style is detected

### Appearence
- [x] on a double click that creates a selection for the editor
- [x] on a mouse-clicked-creating a selection
- [x] on a Shift+Arrow-creating a selection

### Disappearence
- [x] on a click on the editor
- [x] on blur
- [x] when the selection disappear (by moving the cursor thanks to arrows for example)
- [x] when the selection is removed (by a suppression for example)

### Display
- [x] should be animated thanks to [CSS transitions](https://www.w3schools.com/css/css3_transitions.asp)
- [ ] responsive

## Limits
* Can't use both shortcuts and toggle buttons without desynchronizing toggle buttons highlights. It seems to be related to Angular Material.
* Double click selections cover \_\_text\_\_ but not \*\*text\*\* (example), so the use of the toolbar in these cases is a bit limited

**Comment by menou2u** [comment]
A way to achieve this task : http://codemirror.net/doc/manual.html#keymaps
