### ISSUE TITLE
As a User I want to add basic styles (bold,  italic...) to the document using keyboard shortcuts

### ISSUE THREAD

**Issue by kalitine** [coast-team/mute#21]
Find below details about features allowed by shortcuts.

# Existing shortcuts
#### all the #+space, etc... are not considered as shortcuts here
* Ctrl+B: adding bold (\_\_text\_\_)
* Ctrl+I: adding emphasis (\_text\_)
* Ctrl+Alt+S: adding strikethrough (\~\~text\~\~)
* Ctrl+K : generate link syntax ([text](url to add)]

# Features
## Adding style
- [x] bold
- [x] emphasis
- [x] links (puts focus on the url part of the syntax so the user can modify it in any case)
- [x] strikethrough
- [x] adding style through several lines

### If selection is formatted [balise]text[balise]
- [x] bold
- [x] bold written \*\*text\*\*
- [x] emphasis
- [x] emphasis written \*text\*
- [x] strikethrough
- [x] removing a style from a combination of nested ones (e.g.: can remove bold from \_\*\*text\*\*\_) [1]
- [x] removing style through several lines

[1] tests were done thanks to this [file](https://github.com/coast-team/mute/files/1124626/tests.for.shortcuts.txt). If there are missing scenarios please notice it.

## Other
- [x] links : if the link is already set : put focus on the url part of the syntax so the user can modify it

**Comment by menou2u** [comment]
Ways to achieve this task :
* http://codemirror.net/doc/manual.html#keymaps
* https://github.com/sparksuite/simplemde-markdown-editor/commit/131e5d8beb2f51763acd247045bc7ef50fd5c235
* https://codepad.co/snippet/AFTDY5pS
