### ISSUE TITLE
Show version number

### ISSUE THREAD

**Issue by oster** [coast-team/mute#52]
It would be great to know which version of mute (commit id? build number?) we are currently using.

**Comment by kalitine** [comment]
You mean to show it in https://coast-team.github.io/mute somewhere?

**Comment by oster** [comment]
Yes exactly. In a bottom corner for instance. This is something we could disable in production mode for instance. This would be nice to have and provide this information when we are reporting bug.

**Comment by oster** [comment]
Great!

But I prefer that the link points to https://github.com/coast-team/mute/**tree**/{HASH} rather than https://github.com/coast-team/mute/**commit**/{HASH}
