### ISSUE TITLE
Document title is not propagated to other users

### ISSUE THREAD

**Issue by oster** [coast-team/mute#55]
Currently the document is not saved locally (of course, since there is no storage). But, it is not propagated to other users. I mean it should be. 
But how do you plan to deal with concurrent changes on this property which? Do you plan to manage it as a string or as a register?

**Comment by kalitine** [comment]
I think as a register is a better choice for this purpose.

**Comment by oster** [comment]
Sure, I would propose to use a CRDT register and maybe offering support for selecting (overwriting) when concurrent updates on the title were performed.

**Comment by kalitine** [comment]
Resolved.
