### ISSUE TITLE
Add a configuration parameter to define signaling server URL

### ISSUE THREAD

**Issue by oster** [coast-team/mute#56]
I would like to setup a different signaling server (instead of the default one) from a configuration file.  This parameter object should be passed as parameter to the `netflux.create()` method (https://github.com/coast-team/netflux/blob/master/src/index.js#L17).

**Comment by kalitine** [comment]
Now network is looking for signalingURL parameter in the environments/environment.ts file to initialize WebChannel. I've added the environment.demo.ts to the same folder as environment.ts and environment.prod.ts files.

To use this config file do the following:

`ng build -e=demo`
or
`ng serve -e=demo`

In place of `-e=demo` it could be `-e=prod` or `-e=dev`. `-e=dev` is by default for dev target and `-e=prod` by default for prod target. The target is for exemple: `ng server --target=prod`. The default target is `prod`.
