### ISSUE TITLE
Make Offline-first

### ISSUE THREAD

**Issue by kalitine** [coast-team/mute#68]
**Current behavior**
MUTE is distributed all at once (no lazy-loading) from the host like most of the website and web-applications. If the user is not connected to the Internet he is not able to get MUTE.

**Expected behavior**
Once the user got MUTE from for example http://www.coedit.re, then he went offline and refresh the page, he is still able to load MUTE and use it normally (without collaboration of course).

**What is the motivation / use case for changing the behavior?**
This is a particular useful feature for MUTE, because the application allow users to work alone on a document, then merge theirs modifications with other collaborators and, then again work alone and so on. Thus this feature puts in light this MUTE strength.

**Tips**
Check: https://github.com/pazguille/offline-first

**Comment by quentin-tardivon** [comment]
Using sw-precache plugin to generate a Service-Worker.
