### ISSUE TITLE
Sometimes Ctrl+A shortcut does not cover all the text

### ISSUE THREAD

**Issue by menou2u** [coast-team/mute#96]
While I was testing my shortcuts ( #21 ), I've found a scenario where Ctrl+A does not cover all the text. See below :
Here is a text without any style. Ctrl+A renders well.
![image](https://user-images.githubusercontent.com/22363736/27862111-06e17d94-6184-11e7-9dea-cd2c6b9ceba2.png)

After adding a first style to the text (Ctrl+B), Ctrl+A does not cover the first line anymore.
![image](https://user-images.githubusercontent.com/22363736/27862125-140eb3ec-6184-11e7-95e6-8e7c0654f385.png)

However, any other shortcut used on this text (here Ctrl+Alt+S) proves that Ctrl+A considered the whole text anyway.
![image](https://user-images.githubusercontent.com/22363736/27862194-6128854a-6184-11e7-90ef-ac44d6ab61ce.png)

So it seems to "just" be a display bug.

**Comment by menou2u** [comment]
HyperMD has the same problem

**Comment by kalitine** [comment]
Resolved.
